{{- if .Values.scheduler.enabled }}
{{- if and .Values.scheduler.istio.enabled (eq (include "application.scheduler.istio.mode" .) "ambient") .Values.scheduler.istio.waypoint.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.scheduler.istio.waypoint.name | default (include "application.scheduler.name" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "application.scheduler.labels" . | nindent 4 }}
    istio.io/waypoint-for: {{ .Values.scheduler.istio.waypoint.for | default "all" }}
spec:
  gatewayClassName: istio-waypoint
  listeners:
    - name: mesh
      port: 15008
      protocol: HBONE
{{- end }}
{{- end }}
